# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - stable
  paths:
    exclude:
    - azure-pipelines.yml

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/Musicio.Server/Musicio.Server.csproj'

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        command: 'test'
        projects: '**/Musicio.Server.Tests/Musicio.Server.Tests.csproj'

- stage: Release
  displayName: Release stage

  jobs:
  - job: Release
    displayName: Release to Azure

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish the project
      inputs:
        command: 'publish'
        publishWebProjects: true

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(c84a8ed9-acd7-42ac-97cb-252be8ff6ec9)'
        appType: 'webApp'
        WebAppName: 'musicio'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
